---
title: "Cookout Combinatorics"
author: "Joe DiNoto"
date: "9/27/2020"
output: 
  html_document: 
    number_sections: yes
    keep_md: yes
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Cookout Data

## Packages 
```{r warning=FALSE, message=FALSE}
library(tidyverse)
library(ExPanDaR) # allows for easy permutations
```

## load the data
```{r warning=FALSE}
cookout <- read.csv("cookout.csv")  # read csv file
cookout %>% tibble() # convert to tibble
# cookout<-cookout %>% mutate_at(vars(Food.Type,Flavor.Strength), factor)
cookout
```

## use expand() to find permutations
```{r}
# all unique combinations of names, food types and flavor strengths
# nesting() outputs only combinations that already appear in the data
flavor<- cookout %>% expand(nesting(Name, Food.Type, Flavor.Strength))
flavor
```
## hamburgers 2 flavor strength preferences
```{r}
# list of names who have 2 flavor strength preferences for hamburgers
hamburger_names <- flavor %>% filter(Food.Type == "hamburger") %>%
  count(Name, sort=TRUE) %>%
  filter(n==2) %>%
  count(Name) %>%
  select(Name)
hamburger_names
```

## Ice Cream 2 flavor strength preferences

```{r}
# list of names who have 2 flavor strength preferences for ice cream
ice_cream_names <- flavor %>% filter(Food.Type == "ice cream") %>%
  count(Name, sort=TRUE) %>%
  filter(n==2) %>%
  count(Name) %>%
  select(Name)
ice_cream_names
```


```{r}
#Filter the list to hamburger names with two flavor strength preferences
hamburger_toppings <- cookout %>% filter(Food.Type == "hamburger") %>%
  filter(Name %in% ice_cream_names$Name)
hamburger_toppings
```

## Two flavor strengths for Hamburgers

```{r}
top_vec2<-c() # initializes blank vector

cookout <-cookout %>% filter(Name %in% hamburger_toppings$Name) %>% 
  filter(Food.Type=="hamburger") %>%
  arrange(Name,Food.Type,Flavor.Strength,Toppings) # sorts toppings a to z so we don't have xy yx problems.

for(k in 1:(nrow(cookout)-1)){
  for(i in (k+1):(nrow(cookout))){
  if(
    (cookout$Name[k]==cookout$Name[i]) && 
    (cookout$Food.Type[k] == cookout$Food.Type[i]) && 
    (cookout$Flavor.Strength[k] != cookout$Flavor.Strength[i])
    ){
    z <- data.frame(
      name = c(cookout$Name[k]),
      food = c(cookout$Food.Type[k]),
      combo = c(paste(cookout$Toppings[k],cookout$Toppings[i],sep=",")))
    top_vec2 <- rbind(top_vec2,z)
    }
  }
}

```

## let's look at our results for hamburgers!

```{r}
top_vec2 %>% 
  tibble()%>% 
  group_by(food,combo) %>% 
  summarise(count=n()) %>%
  arrange(desc(count)) %>%
  filter(count>1)
```
```{r}
cookout %>% arrange(Name,Food.Type,Flavor.Strength,Toppings)
```
## Misc Notes and such 

```{r}

# sets up counter for names
# unique_names <- unique(cookout$Name)
# n <- length(unique_names) 
# nrow(cookout) # number of rows in the cookout tibble

    #testing purposes
    #x <- paste(cookout$Name[k],cookout$Toppings[k],k,cookout$Toppings[i],i,sep=",")
    #top_vec <- append(top_vec,x)
    # This will give me a vector of (food type, combos within that food type)
    #y <- paste(cookout$Food.Type[k],cookout$Toppings[k],cookout$Toppings[i],sep=",")
    #top_vec <- append(top_vec,y)
    #let's make this a proper tibble?
```

